import { Language, Translation, TeamMember } from './types';

export const TEXTS: Record<'RU' | 'EN', Translation> = {
  RU: {
    navCompany: "КОМПАНИЯ",
    navProject: "ПРОЕКТ",
    navWallet: "КОШЕЛЕК",
    navMainSite: "ГЛАВНЫЙ САЙТ",
    contactBtn: "СВЯЗАТЬСЯ",
    marqueeLBMABench: "LBMA БЕНЧМАРК",
    marqueeSpotAU: "SPOT AU",
    marqueeInstLevel: "ИНСТИТУЦИОНАЛЬНЫЙ УРОВЕНЬ",
    marqueeLivePhysical: "ФИЗИЧЕСКИЙ МЕТАЛЛ",
    companyTitle: "Imperial Pure Gold",
    companySubtitle: "ЗОЛОТОЙ СТАНДАРТ ПРОЗРАЧНОСТИ И БЕЗОПАСНОСТИ В ЭПОХУ ЦИФРОВИЗАЦИИ",
    companyDescTitle: "Imperial Pure Gold DMCC",
    companyDescText1: "Мы — лицензированная компания в самом сердце мирового золотого хаба DMCC (Дубай). Наша миссия — создание безупречных, этичных и высокодоходных цепочек поставок физического золота, соединяющих богатейшие месторождения Африки с глобальными финансовыми центрами Ближнего Востока.",
    companyDescText2: "Imperial Pure Gold DMCC — это не просто торговый дом. Это архитектура доверия, где каждый грамм металла проходит строжайший комплаенс, а каждая транзакция защищена международным правом и инновационными технологиями мониторинга активов.",
    licenseTitle: "РЕГУЛИРОВАНИЕ И ПРАВО",
    licenseDownload: "СКАЧАТЬ ЛИЦЕНЗИЮ",
    licenseView: "ПОСМОТРЕТЬ",
    leadershipTitle: "СОВЕТ ДИРЕКТОРОВ",
    externalLinkText: "ОФИЦИАЛЬНЫЙ ПОРТАЛ IMPERIALPUREGOLD.AE",
    managerTitle: "Ваш персональный менеджер",
    managerDesc: "Получите профессиональную консультацию по вопросам инвестиций и партнерства. Мы на связи 24/7.",
    managerTelegramSub: "Прямой чат в Telegram",
    managerWhatsappSub: "Связаться в WhatsApp",
    menuDashboard: "Личный Кабинет",
    menuCompany: "О Компании",
    menuProject: "Инвестиционный Проект",
    menuCalculator: "Калькулятор Доходности",
    menuCompanySite: "Сайт Корпорации",
    projectTabAbout: "СТРАТЕГИЯ",
    projectTabToken: "ТОКЕНИЗАЦИЯ",
    projectTitle: "ЭКОСИСТЕМА БУДУЩЕГО",
    projectDesc: "Наш проект — это синергия реального сектора (добыча и аффинаж золота) и передовых финтех-решений. Мы устраняем барьеры между частным капиталом и рынком драгоценных металлов, предоставляя инструменты, которые раньше были доступны только институциональным игрокам.",
    telegramBtn: "КАНАЛ СООБЩЕСТВА",
    tokenTitle: "АКТИВ GHS (GOLDEN SHARE)",
    tokenDesc: "GHS — это цифровой сертификат владения, неразрывно связанный с операционной деятельностью Imperial Pure Gold. Это ваш ключ к доле в прибыли от реального оборота золота, защищенный неизменяемостью блокчейна.",
    tokenFeature1: "100% обеспечение физическим металлом",
    tokenFeature2: "Ежеквартальное распределение прибыли",
    tokenFeature3: "Аудит в режиме реального времени",
    walletBtn: "ПЕРЕЙТИ В КОШЕЛЕК",
    footerCompliance: "КОМПЛАЕНС",
    footerNetwork: "КОНТАКТЫ",
    footerSupport: "VIP Поддержка",
    footerDesc: "Imperial Pure Gold DMCC предоставляет доступ к институциональным инвестиционным инструментам на базе золота, обеспечивая безупречную ликвидность и стабильную доходность в любых рыночных условиях.",
    rights: "Все права защищены.",
    footerPrivacy: "Конфиденциальность",
    footerRisk: "Риски",
    footerTerms: "Условия",
  },
  EN: {
    navCompany: "COMPANY",
    navProject: "PROJECT",
    navWallet: "WALLET",
    navMainSite: "MAIN SITE",
    contactBtn: "CONTACT",
    marqueeLBMABench: "LBMA BENCHMARK",
    marqueeSpotAU: "SPOT AU",
    marqueeInstLevel: "INSTITUTIONAL GRADE",
    marqueeLivePhysical: "PHYSICAL ASSET",
    companyTitle: "Imperial Pure Gold",
    companySubtitle: "THE GOLD STANDARD OF TRANSPARENCY AND SECURITY IN THE DIGITAL ERA",
    companyDescTitle: "Imperial Pure Gold DMCC",
    companyDescText1: "We are a licensed entity at the heart of the global gold hub, DMCC Dubai. Our mission is to build flawless, ethical, and high-yield physical gold supply chains connecting Africa's richest deposits with the Middle East's global financial centers.",
    companyDescText2: "Imperial Pure Gold DMCC is more than just a trading house. It is an architecture of trust, where every gram of metal undergoes rigorous compliance, and every transaction is protected by international law and innovative asset monitoring technologies.",
    licenseTitle: "REGULATION & LEGAL",
    licenseDownload: "DOWNLOAD LICENSE",
    licenseView: "VIEW",
    leadershipTitle: "BOARD OF DIRECTORS",
    externalLinkText: "OFFICIAL PORTAL IMPERIALPUREGOLD.AE",
    managerTitle: "Personal Relationship Manager",
    managerDesc: "Receive professional consultation on investment and partnership opportunities. Available 24/7.",
    managerTelegramSub: "Direct Telegram Chat",
    managerWhatsappSub: "Contact via WhatsApp",
    menuDashboard: "Investor Dashboard",
    menuCompany: "About Company",
    menuProject: "Investment Project",
    menuCalculator: "Yield Calculator",
    menuCompanySite: "Corporate Website",
    projectTabAbout: "STRATEGY",
    projectTabToken: "TOKENIZATION",
    projectTitle: "ECOSYSTEM OF THE FUTURE",
    projectDesc: "Our project is a synergy of the real sector (gold mining and refining) and cutting-edge fintech solutions. We eliminate barriers between private capital and the precious metals market, providing tools previously available only to institutional players.",
    telegramBtn: "COMMUNITY CHANNEL",
    tokenTitle: "GHS ASSET (GOLDEN SHARE)",
    tokenDesc: "GHS is a digital certificate of ownership, inextricably linked to the operational activities of Imperial Pure Gold. It is your key to a share in profits from real gold turnover, protected by the immutability of the blockchain.",
    tokenFeature1: "100% Backed by Physical Metal",
    tokenFeature2: "Quarterly Profit Distribution",
    tokenFeature3: "Real-time On-chain Audit",
    walletBtn: "GO TO WALLET",
    footerCompliance: "COMPLIANCE",
    footerNetwork: "CONTACTS",
    footerSupport: "VIP Support",
    footerDesc: "Imperial Pure Gold DMCC provides access to institutional-grade gold investment vehicles, ensuring flawless liquidity and stable returns in any market conditions.",
    rights: "All Rights Reserved.",
    footerPrivacy: "Privacy",
    footerRisk: "Risks",
    footerTerms: "Terms",
  }
};

export const TEAM: Record<Language, TeamMember[]> = {
  RU: [
    { name: "Rajesh Takurdas Sadhwani", role: "Управляющий по лицензии / Директор", image: "https://picsum.photos/seed/executive1/400/400" },
    { name: "Osman Nasr Mohammed", role: "Операционный директор", image: "https://picsum.photos/seed/executive2/400/400" }
  ],
  EN: [
    { name: "Rajesh Takurdas Sadhwani", role: "License Manager / Director", image: "https://picsum.photos/seed/executive1/400/400" },
    { name: "Osman Nasr Mohammed", role: "Operations Director", image: "https://picsum.photos/seed/executive2/400/400" }
  ]
};
